# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-10 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('data_type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Boolean'), (2, 'Integer'), (3, 'Float'), (4, 'Complex'), (5, 'String')], default=0, verbose_name='Data Type')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Argument',
                'verbose_name_plural': 'Arguments',
            },
        ),
        migrations.CreateModel(
            name='BounceReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
            ],
            options={
                'verbose_name': 'Bounce Reason',
                'verbose_name_plural': 'Bounce Reasons',
            },
        ),
        migrations.CreateModel(
            name='BounceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Bounce Type',
                'verbose_name_plural': 'Bounce Types',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ClickUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
            options={
                'verbose_name': 'Click Url',
                'verbose_name_plural': 'Click Urls',
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, editable=False, help_text='UUID', max_length=36, null=True, unique=True)),
                ('from_email', models.CharField(help_text="Sender's e-mail", max_length=254)),
                ('to_email', models.CharField(help_text="Primiary recipient's e-mail", max_length=254)),
                ('category', models.CharField(blank=True, help_text='Primary SendGrid category', max_length=150, null=True)),
                ('response', models.IntegerField(blank=True, help_text='Response received from SendGrid after sending', null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
            },
        ),
        migrations.CreateModel(
            name='UniqueArgument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_sendgrid.Argument')),
            ],
            options={
                'verbose_name': 'Unique Argument',
                'verbose_name_plural': 'Unique Arguments',
            },
        ),
        migrations.CreateModel(
            name='BounceEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_sendgrid.Event')),
                ('status', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Bounce Event',
                'verbose_name_plural': 'Bounce Events',
            },
            bases=('django_sendgrid.event',),
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_sendgrid.Event')),
            ],
            options={
                'verbose_name': 'Click Event',
                'verbose_name_plural': 'Click Events',
            },
            bases=('django_sendgrid.event',),
        ),
        migrations.CreateModel(
            name='DeferredEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_sendgrid.Event')),
                ('response', models.TextField()),
                ('attempt', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Deferred Event',
                'verbose_name_plural': 'Deferred Events',
            },
            bases=('django_sendgrid.event',),
        ),
        migrations.CreateModel(
            name='DeliverredEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_sendgrid.Event')),
                ('response', models.TextField()),
            ],
            options={
                'verbose_name': 'Deliverred Event',
                'verbose_name_plural': 'Deliverred Events',
            },
            bases=('django_sendgrid.event',),
        ),
        migrations.CreateModel(
            name='DroppedEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_sendgrid.Event')),
                ('reason', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Dropped Event',
                'verbose_name_plural': 'Dropped Events',
            },
            bases=('django_sendgrid.event',),
        ),
        migrations.CreateModel(
            name='EmailMessageAttachmentsData',
            fields=[
                ('email_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attachments', serialize=False, to='django_sendgrid.EmailMessage')),
                ('data', models.TextField(editable=False, verbose_name='Attachments')),
            ],
            options={
                'verbose_name': 'Email Message Attachment Data',
                'verbose_name_plural': 'Email Message Attachments Data',
            },
        ),
        migrations.CreateModel(
            name='EmailMessageBccData',
            fields=[
                ('email_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bcc', serialize=False, to='django_sendgrid.EmailMessage')),
                ('data', models.TextField(editable=False, verbose_name='Blind Carbon Copies')),
            ],
            options={
                'verbose_name': 'Email Message Bcc Data',
                'verbose_name_plural': 'Email Message Bcc Data',
            },
        ),
        migrations.CreateModel(
            name='EmailMessageBodyData',
            fields=[
                ('email_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='body', serialize=False, to='django_sendgrid.EmailMessage')),
                ('data', models.TextField(editable=False, verbose_name='Body')),
            ],
            options={
                'verbose_name': 'Email Message Body Data',
                'verbose_name_plural': 'Email Message Body Data',
            },
        ),
        migrations.CreateModel(
            name='EmailMessageCcData',
            fields=[
                ('email_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cc', serialize=False, to='django_sendgrid.EmailMessage')),
                ('data', models.TextField(editable=False, verbose_name='Carbon Copies')),
            ],
            options={
                'verbose_name': 'Email Message Cc Data',
                'verbose_name_plural': 'Email Message Cc Data',
            },
        ),
        migrations.CreateModel(
            name='EmailMessageExtraHeadersData',
            fields=[
                ('email_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extra_headers', serialize=False, to='django_sendgrid.EmailMessage')),
                ('data', models.TextField(editable=False, verbose_name='Extra Headers')),
            ],
            options={
                'verbose_name': 'Email Message Extra Headers Data',
                'verbose_name_plural': 'Email Message Extra Headers Data',
            },
        ),
        migrations.CreateModel(
            name='EmailMessageSendGridHeadersData',
            fields=[
                ('email_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sendgrid_headers', serialize=False, to='django_sendgrid.EmailMessage')),
                ('data', models.TextField(editable=False, verbose_name='SendGrid Headers')),
            ],
            options={
                'verbose_name': 'Email Message SendGrid Headers Data',
                'verbose_name_plural': 'Email Message SendGrid Headers Data',
            },
        ),
        migrations.CreateModel(
            name='EmailMessageSubjectData',
            fields=[
                ('email_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subject', serialize=False, to='django_sendgrid.EmailMessage')),
                ('data', models.TextField(editable=False, verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Email Message Subject Data',
                'verbose_name_plural': 'Email Message Subject Data',
            },
        ),
        migrations.CreateModel(
            name='EmailMessageToData',
            fields=[
                ('email_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='to', serialize=False, to='django_sendgrid.EmailMessage')),
                ('data', models.TextField(editable=False, verbose_name='To')),
            ],
            options={
                'verbose_name': 'Email Message To Data',
                'verbose_name_plural': 'Email Message To Data',
            },
        ),
        migrations.AddField(
            model_name='uniqueargument',
            name='email_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_sendgrid.EmailMessage'),
        ),
        migrations.AddField(
            model_name='event',
            name='email_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_sendgrid.EmailMessage'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_sendgrid.EventType'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='arguments',
            field=models.ManyToManyField(through='django_sendgrid.UniqueArgument', to='django_sendgrid.Argument'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='categories',
            field=models.ManyToManyField(to='django_sendgrid.Category'),
        ),
    ]
