# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-07 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_cms', '0001_initial'),
        ('django_sendgrid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='emailgroup',
            field=models.ManyToManyField(to='my_cms.EmailGroup'),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='click_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_sendgrid.ClickUrl'),
        ),
        migrations.AddField(
            model_name='bounceevent',
            name='bounce_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_sendgrid.BounceReason'),
        ),
        migrations.AddField(
            model_name='bounceevent',
            name='bounce_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_sendgrid.BounceType'),
        ),
    ]
